FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV UV_NO_CACHE=1

RUN apt-get update \
  && apt-get install -y python3 python3-dev curl ca-certificates \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && curl -LsSf https://astral.sh/uv/install.sh | sh \
  && ln -s /root/.local/bin/uv /usr/local/bin/uv \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /sandbox

COPY requirements.txt /sandbox
RUN uv pip install --system -r requirements.txt

COPY python_executor.py /sandbox
